"""patterns

Revision ID: a5eb68816171
Revises: c653f5c53048
Create Date: 2020-01-06 18:31:38.866825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eb68816171'
down_revision = 'c653f5c53048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pattern', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'pattern')
    # ### end Alembic commands ###
